### PR TITLE
write component files to dist instead of root, and ignore dist

### PR DESCRIPTION
**Pull request by tsargent**
This will allow us to import components like this in HCM:

```shell
import { Modal } from 'namely-ui'
```
rather than the current

```shell
import Modal from 'namely-ui/dist/overlays/modal'
```

We would just need to keep `main.js` as a kind of manifest.  It require modules from `dist/` and exports them with a name, eg `Modal`.

```javascript
// main.js
var Modal = require('./dist/overlays/modal');
module.exports.Modal = Modal;
````

I've tried this out in HCM by installing this branch of namely-ui and it seems to work.

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@tsargent This can be closed, right?

**Comment by tsargent** [comment]
no, please leave open

**Comment by jasonfellows** [comment]
Should we do this in a gulp task? Might be useful to be able to run the compilation and dist-building step 
on its own.

**Comment by tsargent** [comment]
you can do `npm run postinstall` and it will run this step

**Comment by jasonfellows** [comment]
Wouldn't it be nice to see the css and js tasks in the same file though? Keep that stuff together? We can also make a task called 'clean' using the del package and add that as a dependency. That way, we're not calling rm -rf from an obscure location.

**Comment by tsargent** [comment]
I think this is a task that should be decoupled from gulp.  Its purpose is for now is to build the dist files in HCM.

**Comment by jasonfellows** [comment]
Could you clarify what motivation exists for executing this task outside the gulpfile?

**Comment by tsargent** [comment]
There are plenty of motivations.  I'd rather not clarify right now as this is WIP.

**Comment by tsargent** [comment]
The possibility of eventually switching to webpack is one...

**Pull request merged**
