### PR TITLE
adds vertical alignment utils

### PR DESCRIPTION
**Pull request by tsargent**
Adds top, middle, bottom vertical alignment, for use mostly in table cells.

`.align-middle` is especially useful for table rows with content v-aligned in the middle.

### CODE REVIEW

**Comment by HipsterBrown** [comment]
@tsargent Could you add a description for how & where these utilities will be used?

**Comment by tsargent** [comment]
@HipsterBrown just added a small description.  Fairly self-explanatory, mostly for table cells.

**Comment by HipsterBrown** [comment]
Really looking for more context behind the need. Are all of these utilities required for a certain design you're implementing? Or just a few of them are needed and maybe we'll use the others later?

**Comment by tsargent** [comment]
I actually just need vertical align middle.  Maybe just that one?

**Comment by HipsterBrown** [comment]
That would be a preference, just to limit the utilities to what we know we'll use, and add as needed. 

That's easier than adding it all and removing later, like with our color utilities.

**Comment by tsargent** [comment]
ok here it is with just `.align-middle`

**Comment by HipsterBrown** [comment]
Is `.align-middle` going to be confusing when working with [`.right-align`](https://github.com/namely/styleguide/blob/41c7e79c8b4007d08c91b677ac1bc38f3b16b86b/src/scss/elements/_typography.scss#L59) as well? 

I guess BassCSS has it set this way, so we shouldn't worry about it.

**Comment by tsargent** [comment]
closing this and opening again to master instead of develop

**Pull request closed without merging**
