### PR TITLE
Package config

### PR DESCRIPTION
**Pull request by jasonfellows**
* Removes namely-ui.scss
* All compilation happens on pre-install now
* Includes all currently built components
* Adds sub-indexes
* Re-writes Gulp compile tasks
* Removes `/dist` management from consumer command line
* Adds log for compiled file sizes
* Use passthrough exports for indexes when it makes sense
* Rename some field displayNames to be more human

This pull request requires changes to the HCM repo.

### CODE REVIEW

**Comment by loudhearted** [comment]
:+1: Super excited about this!

**Comment by jasonfellows** [comment]
I'm currently working on the PR for HCM. I don't think we should consider this reviewed until it has a plus from every stakeholder :)

**Comment by HipsterBrown** [comment]
Not sure the cause behind the CI failure but looks good to me when green. :+1:

**Comment by HipsterBrown** [comment]
Re-:+1: because the build it green now.

**Comment by keithpops** [comment]
+1

**Comment by tsargent** [comment]
+1

**Pull request merged**
