### PR TITLE
Simple Select

### PR DESCRIPTION
**Pull request by tsargent**
addresses namely/styleguide#162

A select component with no bells or whistles.  This is intended for use when we just want a `<select>`, but will give us the JS and CSS necessary for Namely styling.  

The select and options are rendered with divs, while a hidden input passes the selected value through the form. 

#### options
Options can be sent through as
- an array: `['New York', 'London', 'San Francisco']` 
- an object: `{1: 'New York', 2: 'London', 3: 'San Francisco'}`
When an object is used, the keys are used for the value of the input.  So if New York is selected, the value is set to 1.  Otherwise, when an array is used, the items are used for the input value.  

#### value
The value of the field.  If an object is used as options, the value should be one of the keys.  If an array is used, the value is one of the items.  Value is optional, or can be set to null.

#### placeholder
An optional string that will appear if no value is set.

#### includeBlank
An empty option so we can set value to null

#### borderColorClass
We want to be able to pass a border color for errors.  We can do this easily on other form elements just on the component in which they're rendered, but since we're using a component here, we need to be able to pass that down.

#### name 
The name attribute of the hidden field, so we can really use the form if we want.

#### onChange
An change handler, which detects a change in `this.state.value`.

I don't know why my gifs are always so crappy, but here's a crappy GIF:
out

note: this PR also has some unrelated built `dist` files, probably because they weren't checked in from another PR

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Looks pretty thorough and flexible to use. Great work and gif! :+1:

**Comment by loudhearted** [comment]
:+1: :+1: :+1:

**Comment by keithpops** [comment]
object / array option is strong af

+1

**Comment by jasonfellows** [comment]
:+1: :)

**Pull request merged**
