### PR TITLE
better modal behavior

### PR DESCRIPTION
**Pull request by tsargent**
addresses https://github.com/namely/styleguide/issues/128

### CODE REVIEW

**Comment by jasonfellows** [comment]
This probably works, but I don't like the idea of manipulating objects outside the component. What about catching scroll events on the overlay and preventing propagation to <body> instead?

**Comment by tsargent** [comment]
@jasonfellows yeah that's much better.  I'll give that a shot

**Comment by HipsterBrown** [comment]
:+1: for catching scroll events.

**Comment by tsargent** [comment]
closing this and opening to master

**Pull request closed without merging**
