### PR TITLE
Sizing Harmony

### PR DESCRIPTION
**Pull request by jasonfellows**
Refactor to enforce multiplier rule for sizing variables.

The benefits of using only box-model size variables that are divisible by the smallest sizing unit are:
* Potential for UI theming later on
* Elements snap together like legos
* Visual harmony

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Can you post a screenshot of any visual changes?

**Comment by jasonfellows** [comment]
This is an actual refactor, so no visual changes, just keeping existing ratios intact as a rule.

**Comment by HipsterBrown** [comment]
Oh neat. Just wanted to verify that. :+1:

**Comment by naush** [comment]
:+1: Looks good, get it in.

**Pull request merged**
