### PR TITLE
Separate Theme from Utils

### PR DESCRIPTION
**Pull request by jasonfellows**
To provide a theme stylesheet or 'Namely Bootstrap', we need to decouple the CSS from our React components. We have a great library of utility classes that can greatly reduce the footprint of our compiled stylesheet, but we also need to provide styles for native DOM nodes and CSS modules to reduce development effort and enforce design consistency. The balance between compiled asset size and ease of use is important and I think we're getting close to the sweet spot.

Modular systems tend to be better for a lot of reasons, so this PR also sets us up to modularize the 'Bootstrap' part of the styleguide repo. This is primarily a refactor PR. All selectors and rules are still accounted for, just re-arranged. Here is the proposed directory structure:
```
scss
|_animations
|_base
|_layouts
|_theme
   |_elements
   |_modules
```

As usual, each folder has an 'index' file that imports all of it's siblings, all the way down the tree. All thematic CSS is collected into `theme`. `elements` contains styles related to native DOM. `modules` contains visual modules from the Namely style guide.

Also included are a few CSS modules that we needed for our internal tools. Those are enumerated in the CHANGELOG below. 

CHANGELOG:
- separating css theme from utility classes
- removing unused react-select
- correcting hover border-color bug for inputs
- correcting border-box for inputs for matching sizing units
- adjusting check size to center
- adding back link style module
- adding nav style modules
- adding flash messaging style module
- supporting button styles for input[type="submit"] and input[type="button"]
- sorting funtions in router alphabetically

### CODE REVIEW

**Comment by HipsterBrown** [comment]
Does this introduce any breaking changes to how HCM consumes this package?

**Comment by jasonfellows** [comment]
@HipsterBrown No, its mostly just moving some files around. There are still a bunch of CSS modules to add in future PRs. This gathers the modules in one place and adds a few I needed for the internal tools.

**Comment by jasonfellows** [comment]
Simplified this a lot. Moving the utility classes out of the namespace might have caused some side-effects. The last few commits should have removed all possibility of that.

**Comment by jasonfellows** [comment]
@tsargent @HipsterBrown @loudhearted @katienreed @keithpops 
Can you review when you have time?

**Comment by jasonfellows** [comment]
Another important note: this branch has been pushed to the namely fork and is currently being used in HAT an Koala Konsole.

**Comment by tsargent** [comment]
I don't think we should be introducing any changes right now.  If you want to fork namely-ui in order to use it elsewhere, go for it.  I think we need to focus on tearing this apart, not adding to it.

**Comment by jasonfellows** [comment]
@tsargent The only things added are those nav styles, which allow us to prevent duplicate styles in three different apps.

The rest of the PR organizes the stylesheets with different uses into folders, making them easier to 'tear apart' into different stylesheets later if the need arises.

**Comment by keithpops** [comment]
I would second the fork suggestion. QA is going to have a hard time with any more NUI releases that find their way into HCM no matter the reason until we have a clear workflow process they can follow, are involved in, and understand the changes coming through the pipeline. If it is a matter of trying to avoid multiple styles, I'd document which ever component is going to be the source of truth somewhere in Confluence so it's on our radar while we consider our roadmap and workflow going forward.

**Comment by jasonfellows** [comment]
I'll make another PR simply adding the modules needed for the internal tools. Using my Github account for another fork is a bad suggestion since I won't be in the organization after May 4th.

**Comment by keithpops** [comment]
No I wouldn't suggest keeping it on a personal account. If forking is an issue just clone to another repo under the Namely account and we'll deal with it later.

**Comment by jasonfellows** [comment]
It's not a problem, guys. I'll make another PR with just the CSS modules. That way, there is nothing to do later.

**Pull request closed without merging**
