### PR TITLE
FieldBase

### PR DESCRIPTION
**Pull request by jasonfellows**

### CODE REVIEW

**Comment by HipsterBrown** [comment]
:+1:

**Comment by tsargent** [comment]
what does this do?

**Comment by jasonfellows** [comment]
@tsargent This is a parent class to encapsulate the commonalities shared between fields regardless of type, such as interface and errors. We were defining a lot of the same props for each field over and over again. This allows us to do that in one place. This is the result of the meeting we all had after field errors were added to SimpleSelect.

**Comment by jasonfellows** [comment]
I was going to write a description once I was ready for the RFC flag. Nick just changed those and I'm still not sure this is finished.

**Comment by HipsterBrown** [comment]
@jasonfellows What is missing that you feel makes it unfinished?

**Pull request closed without merging**
