### PR TITLE
F/add calculator

### PR DESCRIPTION
**Pull request by tsargent**
oy

wip...

### CODE REVIEW

**Comment by tsargent** [comment]
anyone know if this looks wrong, since all the codepoints and unicode characters changed around where the calculator was added?  @HipsterBrown @jasonfellows @keithpops @loudhearted @katienreed This is confusing the hell out of me. :)  The use of icomoon with the gulp icons task is still really unclear to me.

**Comment by jasonfellows** [comment]
I think only one of the font formats will import while preserving the original unicode characters. Unfortunately, I can't remember which one off the top of my head.

**Comment by tsargent** [comment]
I'm just going to use the svg and forget about the font.  LATER!

**Comment by jasonfellows** [comment]
I'd rather do it the right way to keep icon logic familiar. Want to pair on it?

**Pull request closed without merging**
