### PR TITLE
Goodbye dist/

### PR DESCRIPTION
**Pull request by HipsterBrown**
This PR updates the `prepublish` task under the npm scripts in `package.json` to use a new bash script for moving all components into the root level of the namely-ui directory when installed. This way we can remove `dist/` from git and this repo, and make importing components a bit cleaner, i.e. 
```js
import Button from 'namely-ui/buttons/button'
```
I will also be renaming all the component files to use the `.es6` extension that is standard in HCM, so that there is no need to process those files before publishing.

### CODE REVIEW

**Comment by tsargent** [comment]
I'll miss you, `dist/`.  You were always full of surprises.  :cry:

**Comment by jasonfellows** [comment]
+1 (million)

**Comment by loudhearted** [comment]
:+1:

**Comment by tsargent** [comment]
has this been tested in HCM?  Like when you do `npm install` within the rails app.

**Pull request merged**
